apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-onboarding-config
data:
  AZURE_SUBSCRIPTION_IDS: "7f3c2a1d-4e8b-4f9c-a2d1-3b5e6f7a8c9d, 33333333-3333-3333-3333-333333333333, 7c8d9e0f-1a2b-4c3d-e4f5-a6b7c8d9e0f1"
  EVENTHUBS: "product1-diagnostics-prd-euw-logs, product2-diagnostics-prd-euw-logs, team2-dataproc-prd-euw-logs, team8-dataproc-prd-euw-logs, team7-dataprocess-prd-euw-logs, team4-ddflows-prd-euw-logs, teemo-tall-prd-euw-logs, onepiece-zoro-prd-euw-logs, zet-mart-prd-euw-logs"  
