apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-onboarding-config
data:
  AZURE_SUBSCRIPTION_IDS: "7f3c2a1d-4e8b-4f9c-a2d1-3b5e6f7a8c9d, 9e0f1a2b-3c4d-4e5f-a6b7-c8d9e0f1a2b3, 2d3e4f5a-6b7c-4d8e-9f0a-1b2c3d4e5f6a"
  EVENTHUBS: "product1-diagnostics-int-euw-logs, product2-diagnostics-int-euw-logs, team2-dataproc-int-euw-logs, team8-dataproc-int-euw-logs, team7-dataprocess-int-euw-logs, team4-ddflows-int-euw-logs"  
